project_id = "rwagvawmceempafacnfh"

[functions.unipile-lookup]
verify_jwt = false

[functions.enrich-lead]
verify_jwt = false

[functions.webhooks-apify]
verify_jwt = false

[functions.webhooks-apollo]
verify_jwt = false

[functions.whatsapp-connect]
verify_jwt = false

[functions.webhooks-whatsapp]
verify_jwt = false

[functions.process-campaign-queue]
verify_jwt = false

[functions.webhooks-linkedin]
verify_jwt = false