project_id = "rwagvawmceempafacnfh"

[functions.unipile-lookup]
verify_jwt = false

[functions.enrich-lead]
verify_jwt = false

[functions.webhooks-apify]
verify_jwt = false

[functions.webhooks-apollo]
verify_jwt = false

[functions.whatsapp-connect]
verify_jwt = false

[functions.webhooks-whatsapp]
verify_jwt = false

[functions.process-campaign-queue]
verify_jwt = false

[functions.webhooks-linkedin]
verify_jwt = false

[functions.connect-account]
verify_jwt = false

[functions.webhooks-integration]
verify_jwt = false

[functions.apollo-search]
verify_jwt = false

[functions.redirect-link]
verify_jwt = false

[functions.send-click-notification]
verify_jwt = false

[functions.unipile-messages]
verify_jwt = false

[functions.unipile-webhook]
verify_jwt = false

[functions.enrich-batch-leads]
verify_jwt = false

[functions.track-click]
verify_jwt = false

[functions.process-workflow-batch]
verify_jwt = false